name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Usando Nodejs versão ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}  
    - name: npm install e test
      run: |
        npm ci
        npm test
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.accessKeyId }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.secretAccessKey }}